### ISSUE TITLE
Story: Create gallery of space images

### ISSUE THREAD

**Issue by AmandaGuerriero** [rawagschal/spaced-out#14]
### User Story
As a fan of space, I want to view images from space, because I want to view more than just the image of the day

### Acceptance Criteria
Given I'm a fan of space
When I visit Spaced Out
Then I view a button to view all space media
When I select that button
Then I am taken to a gallery of space images

**Comment by rawagschal** [comment]
will create a new issue for grid styling but moving on to modal for now.
